// This file will be generated by: npx supabase gen types typescript --local > lib/supabase/types.ts
// For now, we'll define basic types manually

export interface Database {
  public: {
    Tables: {
      newsletter_subscribers: {
        Row: {
          id: string
          email: string
          status: 'pending' | 'confirmed' | 'unsubscribed'
          subscribed_at: string
          confirmed_at: string | null
          unsubscribed_at: string | null
        }
        Insert: {
          email: string
          status?: 'pending' | 'confirmed' | 'unsubscribed'
        }
        Update: {
          email?: string
          status?: 'pending' | 'confirmed' | 'unsubscribed'
          confirmed_at?: string | null
          unsubscribed_at?: string | null
        }
      }
      contact_submissions: {
        Row: {
          id: string
          first_name: string
          last_name: string
          email: string
          phone: string
          message: string | null
          submitted_at: string
          status: 'new' | 'contacted' | 'qualified' | 'closed'
          assigned_to: string | null
        }
        Insert: {
          first_name: string
          last_name: string
          email: string
          phone: string
          message?: string | null
          status?: 'new' | 'contacted' | 'qualified' | 'closed'
        }
        Update: {
          status?: 'new' | 'contacted' | 'qualified' | 'closed'
          assigned_to?: string | null
        }
      }
      team_members: {
        Row: {
          id: string
          name: string
          role: string
          bio: string
          image_url: string | null
          display_order: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          name: string
          role: string
          bio: string
          image_url?: string | null
          display_order: number
          is_active?: boolean
        }
        Update: {
          name?: string
          role?: string
          bio?: string
          image_url?: string | null
          display_order?: number
          is_active?: boolean
        }
      }
      service_offerings: {
        Row: {
          id: string
          title: string
          description: string
          icon: string | null
          display_order: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          title: string
          description: string
          icon?: string | null
          display_order: number
          is_active?: boolean
        }
        Update: {
          title?: string
          description?: string
          icon?: string | null
          display_order?: number
          is_active?: boolean
        }
      }
    }
  }
}